# Generated by Django 5.2.5 on 2025-08-19 07:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('composer', models.CharField(blank=True, max_length=255)),
                ('instrumentation', models.CharField(blank=True, max_length=255)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('size_bytes', models.BigIntegerField()),
                ('mime', models.CharField(default='application/pdf', max_length=100)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags for categorizing scores', size=None)),
                ('note', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 hash of file content for deduplication', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scores_user_id_bf2900_idx'), models.Index(fields=['content_hash'], name='scores_content_0b32b0_idx'), models.Index(fields=['title'], name='scores_title_af72e3_idx')],
            },
        ),
    ]
