# Generated by Django 5.0.14 on 2026-09-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ensembles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ensembles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='비우면 만료 없음', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='비우면 횟수 제한 없음', null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='ensembles.ensemble')),
            ],
            options={
                'db_table': 'ensemble_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('leader', 'Leader'), ('member', 'Member')], default='member', max_length=10)),
                ('part', models.CharField(blank=True, help_text='예: "Guitar 1", "총보"', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ensembles.ensemble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ensemble_memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['user', 'role'], name='ensemble_me_user_id_0335fe_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('ensemble', 'user'), name='unique_ensemble_member'),
        ),
    ]
