# Generated by Django 5.2.5 on 2025-08-19 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'setlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SetlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Performance notes for this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_items', to='scores.score')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='setlists.setlist')),
            ],
            options={
                'db_table': 'setlist_items',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['user', '-updated_at'], name='setlists_user_id_78f58c_idx'),
        ),
        migrations.AddIndex(
            model_name='setlistitem',
            index=models.Index(fields=['setlist', 'order_index'], name='setlist_ite_setlist_eda258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='setlistitem',
            unique_together={('setlist', 'score')},
        ),
    ]
