# Generated by Django 5.2.17 on 2026-09-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0001_initial'),
        ('setlists', '0002_alter_setlistitem_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setlists', to='ensembles.ensemble'),
        ),
    ]
