# Generated by Django 5.2.17 on 2026-09-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
