# Generated by Django 5.2.17 on 2026-09-27 13:39

import django.db.models.deletion
from django.db import migrations, models


def keep_existing_devices_on_all(apps, schema_editor):
    """Devices linked before this change keep receiving all scores; new devices default to selected setlists."""
    Device = apps.get_model('devices', 'Device')
    Device.objects.update(sync_mode='all')


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_synced_at'),
        ('setlists', '0003_setlist_ensemble'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sync_mode',
            field=models.CharField(choices=[('setlists', 'Selected setlists only'), ('all', 'All scores')], default='setlists', max_length=10),
        ),
        migrations.CreateModel(
            name='DeviceSetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_links', to='devices.device')),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to='setlists.setlist')),
            ],
            options={
                'db_table': 'device_setlists',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='sync_setlists',
            field=models.ManyToManyField(blank=True, related_name='+', through='devices.DeviceSetlist', to='setlists.setlist'),
        ),
        migrations.AddConstraint(
            model_name='devicesetlist',
            constraint=models.UniqueConstraint(fields=('device', 'setlist'), name='unique_device_setlist'),
        ),
        migrations.RunPython(keep_existing_devices_on_all, migrations.RunPython.noop),
    ]
