# Generated by Django 5.2.17 on 2026-09-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_sync_setlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='sync_mode',
        ),
    ]
