"""
Django settings for scoremateserver project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

from .version import VERSION  # noqa: E402

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG')

_DEV_SECRET_KEY = 'django-insecure-4*j867jb0*b1&b7fx6wb6+7%d8nwb5sjcgq9q5ziqhls*2vpqe'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _DEV_SECRET_KEY)
# 운영(REQUIRE_SECRET_KEY=true)에서는 개발용 키 · 짧은 키로 뜨지 않는다 — JWT 서명 키이기도 하다
if env_bool('REQUIRE_SECRET_KEY') and (SECRET_KEY == _DEV_SECRET_KEY or len(SECRET_KEY) < 50):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set to a random value of 50+ characters')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# 앞단 nginx 가 TLS 를 끝내고 X-Forwarded-Proto 를 넘긴다. 리다이렉트는 nginx 담당이라 Django 는 하지 않는다
if env_bool('TRUST_PROXY_HEADERS'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = False
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT')
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE')
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
SECURE_CONTENT_TYPE_NOSNIFF = True

# 개발 웹(Next.js dev 서버)용 CORS 출처. 운영은 같은 출처라 필요 없다 — 비우면 CORS 헤더를 내지 않는다
CORS_ALLOWED_ORIGIN = os.environ.get('CORS_ALLOWED_ORIGIN', 'http://localhost:3000' if DEBUG else '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',

    # Local apps
    'core',
    'ensembles',
    'devices',
    'scores',
    'setlists',
    'files',
    'tasks',
    'scoremate_admin', # Custom admin app
    'web',             # 웹 화면 (Django 템플릿)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # /static/ (admin) — 컨테이너가 직접 낸다
    'core.middleware.CorsMiddleware',  # Add CORS middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Custom middleware
    'core.middleware.SecurityHeadersMiddleware',
    'core.middleware.APILoggingMiddleware',
    'core.middleware.QuotaCheckMiddleware',
]

ROOT_URLCONF = 'scoremateserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoremateserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 기본은 SQLite (dolfinid 배포 관례, 054). DATA_DIR 에 DB 파일을 둔다 — 운영에서는 bind mount.
# DATABASE_URL 을 주면 그것을 쓴다 (예: postgres://…)
DATA_DIR = Path(os.environ.get('DATA_DIR', BASE_DIR / 'data'))
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f"sqlite:///{DATA_DIR / 'db.sqlite3'}"),
        conn_max_age=0 if not os.environ.get('DATABASE_URL') else 600,
    )
}
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    # gunicorn 스레드 여럿이 쓴다 — 잠금은 기다리고, WAL 로 읽기가 쓰기를 막지 않게 (DB 는 디렉터리 마운트라 -wal 이 호스트에 남는다)
    DATABASES['default']['OPTIONS'] = {
        'timeout': 20,
        'transaction_mode': 'IMMEDIATE',
        'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul' # Changed from UTC

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'
                    if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}

# Media files (user uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # simplejwt JWTAuthentication + 해제된 TV 기기의 토큰 거부 (devices/auth.py)
        'devices.auth.DeviceAwareJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'invite': '30/hour',  # 초대 코드 미리 보기 · 가입 — 코드 맞히기 방지
        'device_code': '30/hour',     # TV 코드 발급 (IP 당)
        'device_token': '2000/hour',  # TV 가 5초마다 토큰을 묻는다 (IP 당, 같은 집의 TV 여러 대)
        'sync': '3000/hour',          # 동기화 · 받기 · 분석 — 기기마다(devices.auth.PerDeviceScopedRateThrottle)
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    # 클라이언트(웹 · TV)는 JSON 을 보낸다. 테스트도 같게 (multipart 면 목록 값이 하나만 남는다)
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY', SECRET_KEY), # Use JWT_SIGNING_KEY from env or SECRET_KEY
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

    # 해제된 기기 거부 + 기기 토큰은 회전해도 긴 수명 (devices/serializers.py)
    'TOKEN_REFRESH_SERIALIZER': 'devices.serializers.DeviceAwareTokenRefreshSerializer',
}

# TV 동기화 (scores/sync.py): 한 번에 보낼 악보 수, 늦은 커밋을 놓치지 않게 미루는 시간
SYNC_PAGE_SIZE = int(os.environ.get('SYNC_PAGE_SIZE', 200))
SYNC_LAG_SECONDS = int(os.environ.get('SYNC_LAG_SECONDS', 5))

# TV 기기 토큰의 refresh 수명 — TV 에서 다시 로그인할 일이 거의 없게. 해제하면 곧바로 막힌다
DEVICE_REFRESH_TOKEN_DAYS = int(os.environ.get('DEVICE_REFRESH_TOKEN_DAYS', 180))

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# 웹 로그인 (세션). API 는 JWT
LOGIN_URL = 'web:login'
LOGIN_REDIRECT_URL = 'web:scores'
LOGOUT_REDIRECT_URL = 'web:login'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30   # 한 달 — 리허설 때마다 로그인하지 않게
# Google 로그인 (web/google.py) — 둘 다 있을 때만 켜진다. 승인된 리디렉션 URI: https://<도메인>/auth/google/callback/
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# 가입을 누구에게나 열지 (False 면 웹 · API 가입이 닫히고 초대 링크로 이미 가입한 사람만 쓴다)
REGISTRATION_OPEN = env_bool('REGISTRATION_OPEN', True)

# 큰 업로드는 메모리 대신 디스크 임시 파일로 — 운영은 tmpfs(/tmp) 대신 파일 저장소 옆(FILE_UPLOAD_TEMP_DIR)
FILE_UPLOAD_TEMP_DIR = os.environ.get('FILE_UPLOAD_TEMP_DIR') or None
if FILE_UPLOAD_TEMP_DIR:
    os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# Storage settings (for S3/MinIO)
STORAGE_ENDPOINT = os.environ.get('STORAGE_ENDPOINT')
STORAGE_PUBLIC_ENDPOINT = os.environ.get('STORAGE_PUBLIC_ENDPOINT', STORAGE_ENDPOINT)
STORAGE_BUCKET = os.environ.get('STORAGE_BUCKET')
STORAGE_ACCESS_KEY = os.environ.get('STORAGE_ACCESS_KEY')
STORAGE_SECRET_KEY = os.environ.get('STORAGE_SECRET_KEY')
STORAGE_USE_SSL = os.environ.get('STORAGE_USE_SSL', 'False').lower() == 'true'

# 저장소 백엔드: 's3'(MinIO/S3 presigned URL) | 'local'(FILES_ROOT 디스크 + 서명 토큰 URL, 운영 dolfinid)
STORAGE_BACKEND = os.environ.get('STORAGE_BACKEND', 's3')
FILES_ROOT = Path(os.environ.get('FILES_ROOT', DATA_DIR / 'files'))
# 토큰 URL 경로와 (필요하면) 절대 주소 앞부분. 비우면 같은 출처의 상대 주소
FILES_BLOB_PATH = '/api/v1/files/blob/'
FILES_PUBLIC_BASE = os.environ.get('FILES_PUBLIC_BASE', '').rstrip('/')
# 설정하면 받기를 nginx 에 넘긴다: X-Accel-Redirect: <prefix><key> (nginx 의 internal location)
FILES_X_ACCEL_PREFIX = os.environ.get('FILES_X_ACCEL_PREFIX', '')
# 목록 응답의 썸네일 URL 유효 시간
THUMBNAIL_URL_EXPIRY = int(os.environ.get('THUMBNAIL_URL_EXPIRY', 6 * 3600))

# File Upload settings
MAX_UPLOAD_SIZE = int(os.environ.get('MAX_UPLOAD_MB', 100)) * 1024 * 1024  # Convert to bytes
ALLOWED_MIME_TYPES = os.environ.get('ALLOWED_MIME', 'application/pdf').split(',')
PRESIGNED_URL_EXPIRY = int(os.environ.get('PRESIGNED_URL_EXPIRY', 300))  # 5 minutes

# Quota and Referral settings
MAX_UPLOAD_MB = int(os.environ.get('MAX_UPLOAD_MB', 200))
REFERRAL_BONUS_MB = int(os.environ.get('REFERRAL_BONUS_MB', 50))

# Celery settings (basic setup, more advanced config will be in tasks app)
# REDIS_URL 이 없으면 워커 · Redis 없이 **요청 안에서 바로 실행**한다 (dolfinid 에 컨테이너 하나로 올리기 위해, 054).
# 페이지 수 · 썸네일은 PyMuPDF 로 수백 ms 라 충분하다. 작업이 무거워지면 REDIS_URL 을 주고 워커를 띄우면 원래대로.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
else:
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = None
    CELERY_TASK_ALWAYS_EAGER = True
    # 작업이 실패해도 업로드 요청 자체는 성공시킨다 (작업 결과는 Task 레코드 · 로그에 남는다)
    CELERY_TASK_EAGER_PROPAGATES = False
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Seoul'

# Logging configuration — 기본은 콘솔(컨테이너 로그). LOG_DIR 을 주면 파일에도 쓴다 (운영 컨테이너는 루트가 읽기 전용)
LOG_DIR = os.environ.get('LOG_DIR')
_log_handlers = ['console']
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {'handlers': _log_handlers, 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': _log_handlers, 'level': 'INFO', 'propagate': False},
        **{
            name: {'handlers': _log_handlers, 'level': 'DEBUG' if DEBUG else 'INFO', 'propagate': False}
            for name in ('core', 'scores', 'setlists', 'files', 'tasks', 'ensembles')
        },
    },
}
if LOG_DIR:
    os.makedirs(LOG_DIR, exist_ok=True)
    LOGGING['handlers']['file'] = {
        'level': 'INFO', 'class': 'logging.FileHandler',
        'filename': os.path.join(LOG_DIR, 'scoremate.log'), 'formatter': 'verbose',
    }
    _log_handlers.append('file')
