# Generated by Django 5.0.14 on 2025-08-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename when uploaded', max_length=255),
        ),
    ]
