# Generated by Django 5.0.14 on 2026-09-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0001_initial'),
        ('scores', '0002_score_original_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='ensembles.ensemble'),
        ),
        migrations.AddField(
            model_name='score',
            name='part_name',
            field=models.CharField(blank=True, help_text='e.g. "Full score", "Guitar 1"', max_length=100),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['ensemble', '-created_at'], name='scores_ensembl_233aed_idx'),
        ),
    ]
