# Generated by Django 5.2.17 on 2026-09-27 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_version_1(apps, schema_editor):
    """Every existing score gets version 1 made from its current file fields (idempotent)."""
    Score = apps.get_model('scores', 'Score')
    ScoreVersion = apps.get_model('scores', 'ScoreVersion')
    for score in Score.objects.filter(current_version__isnull=True).exclude(s3_key='').iterator():
        version, _ = ScoreVersion.objects.get_or_create(
            score=score, number=1,
            defaults=dict(
                s3_key=score.s3_key, original_filename=score.original_filename,
                size_bytes=score.size_bytes, mime=score.mime, pages=score.pages,
                content_hash=score.content_hash, uploaded_by_id=score.user_id,
            ),
        )
        # keep the original upload time; queryset.update() leaves auto_now fields alone
        ScoreVersion.objects.filter(pk=version.pk).update(created_at=score.created_at)
        Score.objects.filter(pk=score.pk).update(current_version=version, last_version_number=1)


def unlink_versions(apps, schema_editor):
    Score = apps.get_model('scores', 'Score')
    Score.objects.update(current_version=None, last_version_number=0)




class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_score_ensemble'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='last_version_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('s3_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('mime', models.CharField(default='application/pdf', max_length=100)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of the file', max_length=64)),
                ('note', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scores.score')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_versions',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scores.scoreversion'),
        ),
        migrations.AddConstraint(
            model_name='scoreversion',
            constraint=models.UniqueConstraint(fields=('score', 'number'), name='unique_score_version_number'),
        ),
        migrations.RunPython(backfill_version_1, unlink_versions),
    ]
