# Generated by Django 5.2.17 on 2026-09-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_score_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='arranger',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
